### ISSUE TITLE
Zero values for 5 sensors in PeMS data

### ISSUE THREAD

**Issue by KhaledAlkilane89** [deepkashiwa20/Urban_Concept_Drift#1]
I found five sensors, which are ['402288','402289','402368','402369','404554'], with completely zero values through the whole PeMS dataset!? Any pre-processing for those sensors before using the data?
![Weixin Screenshot_20240205145610](https://github.com/deepkashiwa20/Urban_Concept_Drift/assets/60028253/7e802c8b-1139-4578-b47f-b4d54fd5ecce)

**Comment by deepkashiwa20** [comment]
Thank you for your inquiry regarding the PeMS 2020 dataset. We found that these zeros are due to the absence of data for these nodes in the original dataset released from PeMS. No specific pre-processing was performed on these sensors before making the dataset public.

Our approach to collecting the dataset aimed to maintain consistency and comparability of the data with widely used PeMS-BAY dataset (https://paperswithcode.com/dataset/pems-bay). Only the time frame covered by the data differs.

We appreciate your attention to this matter and suggest users make further necessary changes to the data based on personal analysis or modeling preferences. If you have further questions or need assistance, please feel free to reach out.
